import React from "react";
import { v4 as uuidv4 } from "uuid";
import logo from "../../assets/images/netcentric-logo.png";

import { Document, Page, Text, StyleSheet, View, Font, Image } from "@react-pdf/renderer";
import {
	Table,
	TableHeader,
	TableCell,
	TableBody,
	DataTableCell
} from "@david.kucsai/react-pdf-table";
import { pdfData } from "../../data";

// Create styles
const styles = StyleSheet.create({
	body: {
		padding: 15,
		height: "100%",
		width: "100%",
		position: "relative"
	},
	borderTopInfo: {
		fontSize: 8
	},
	borderBotInfo: {
		fontSize: 8,
		position: "absolute",
		left: 15,
		bottom: 15
	},
	title: {
		fontSize: 20,
		fontFamily: "Open Sans",
		fontWeight: "bold",
		textAlign: "center",
		marginTop: 100
	},
	subtitle: {
		fontSize: 15,
		fontWeight: "bold",
		textAlign: "center",
		margin: 12
	},
	subtitle2: {
		fontSize: 12,
		fontWeight: "bold",
		margin: 12
	},
	textTableTitle: {
		fontSize: 12,
		fontFamily: "Open Sans",
		fontWeight: "bold",
		textAlign: "center",
		padding: 5
	},
	textTableReg: {
		fontSize: 10,
		fontFamily: "Open Sans",
		textAlign: "center",
		fontWeight: "normal",
		padding: 5
	},
	image: {
		position: "absolute",
		top: "5%",
		left: "27.5%",
		transform: "translate(50%,50%)",
		height: "auto",
		width: 150
	},
	header: {
		fontSize: 12,
		marginBottom: 20,
		textAlign: "center",
		color: "grey"
	},
	footer: {
		padding: "100px",
		fontSize: 12,
		marginBottom: 20,
		textAlign: "center",
		color: "grey"
	},
	pageNumber: {
		position: "absolute",
		fontSize: 12,
		bottom: 30,
		left: 0,
		right: 0,
		textAlign: "center",
		color: "grey"
	},
	section1: {
		marginTop: 100
	},
	section2: {
		marginTop: 30
	}
});

Font.register({
	family: "Open Sans",
	src: "https://fonts.gstatic.com/s/opensans/v17/mem8YaGs126MiZpBA-UFVZ0e.ttf"
});

function PdfTable({ fname }) {
	const uniqId = uuidv4();

	return (
		<Document>
			<Page style={styles.body}>
				<Text
					style={
						styles.borderTopInfo
					}>{`Time requested: ${new Date().toLocaleString()} | Transaction Id: ${uniqId} | Generated by: https://peopleware-ets.com/employee/tracker`}</Text>
				<View style={styles.section1}>
					<Image src={logo} style={styles.image} />
					<Text style={styles.title}>Employee Information</Text>
					<Text style={styles.subtitle}>Status Summary</Text>
				</View>
				<Table>
					<TableHeader>
						<TableCell>
							<Text style={styles.textTableTitle}>Company</Text>
						</TableCell>
						<TableCell>
							<Text style={styles.textTableTitle}>Employee Id</Text>
						</TableCell>
						<TableCell>
							<Text style={styles.textTableTitle}>Name</Text>
						</TableCell>
						<TableCell>
							<Text style={styles.textTableTitle}>Position</Text>
						</TableCell>
						<TableCell>
							<Text style={styles.textTableTitle}>End Date</Text>
						</TableCell>
						<TableCell>
							<Text style={styles.textTableTitle}>Status</Text>
						</TableCell>
					</TableHeader>
				</Table>
				<Table data={pdfData}>
					<TableBody>
						<DataTableCell
							getContent={(eData) => <Text style={styles.textTableReg}>{eData.company}</Text>}
						/>
						<DataTableCell
							getContent={(eData) => <Text style={styles.textTableReg}>{eData.employeeId}</Text>}
						/>
						<DataTableCell
							getContent={(eData) => <Text style={styles.textTableReg}>{eData.name}</Text>}
						/>
						<DataTableCell
							getContent={(eData) => <Text style={styles.textTableReg}>{eData.position}</Text>}
						/>
						<DataTableCell
							getContent={(eData) => <Text style={styles.textTableReg}>{eData.endDate}</Text>}
						/>
						<DataTableCell
							getContent={(eData) => <Text style={styles.textTableReg}>{eData.status}</Text>}
						/>
					</TableBody>
				</Table>
				<View style={styles.section2}>
					<Text style={styles.subtitle2}>{`Time requested: ${new Date().toLocaleString()}`}</Text>
					<Text style={styles.subtitle2}>{`Requested By: ${fname} 
`}</Text>
					<Text style={styles.subtitle2}>{`Transaction Id: ${uniqId}`}</Text>
				</View>
				<Text
					style={
						styles.borderBotInfo
					}>{`Time requested: ${new Date().toLocaleString()} | Transaction Id: ${uniqId} | Generated by: https://peopleware-ets.com/employee/tracker`}</Text>
			</Page>
		</Document>
	);
}

export default PdfTable;
